Repository hmcts/wa-case-event-handler, pull requests merged in 2021-07, with the labels that each got.

#164 Fix nightly build failure
  Jenkinsfile_nightly
  security.sh
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-164

#165 Update functional output synthax
  security.sh
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-165

#170 CVE-2021-27568 fix for json-smart library
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-170

#160 Updated warning handler to add warnings as process variables
  charts/wa-case-event-handler/Chart.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerBackwardsCompatibilityTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerEndpointTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java
  src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/camunda/Warning.java
  src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/camunda/WarningValues.java
  src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/camunda/response/CancellationEvaluateResponse.java
  src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationCaseEventHandler.java
  src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/WarningCaseEventHandler.java
  src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/camunda/WarningTest.java
  src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/camunda/WarningValuesTest.java
  src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/CancellationCaseEventHandlerBackwardsCompatibilityTest.java
  src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/CancellationCaseEventHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationCaseEventHandlerBackwardsCompatibilityTest.java
  src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationCaseEventHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/WarningCaseEventHandlerBackwardsCompatibilityTest.java
  src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/WarningCaseEventHandlerTest.java
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-160

#172 Nightly fx
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-172

#171 add swagger api docs
  build.gradle
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/config/SwaggerPublisherTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerBackwardsCompatibilityTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerEndpointTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerHandlersOrderTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerSecurityTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/GetWelcomeTest.java
  src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/config/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerController.java
  src/main/resources/application.yaml
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-171

#178 Fix Nighly build
  audit.json
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-178

#176 Supporting Non-IAC requirements for warn events
  charts/wa-case-event-handler/Chart.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/WarningEventHandlerControllerTest.java
  src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/camunda/response/CancellationEvaluateResponse.java
  src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/WarningCaseEventHandler.java
  src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/camunda/response/CancellationEvaluateResponseTest.java
  src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/WarningCaseEventHandlerBackwardsCompatibilityTest.java
  src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/WarningCaseEventHandlerTest.java
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-176
