Repository hmcts/wa-case-event-handler, pull requests merged in 2021-11, with the labels that each got.

#193 RWA-890 [SH] Fixing CVE-2021-22096 by bumping springboot version
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-193

#194 RWA-776 added ithc and perftest to be in sync with master
  .gitignore
  Jenkinsfile_CNP
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-194

#195 RWA-913 Configure the DB creation
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-195
