Repository hmcts/wa-case-event-handler, pull requests merged in 2023-10, with the labels that each got.

#647 RWA-2765-upgrade java logging
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-647

#650 RWA-2856- wa-case-event-handler master pipeline build failure
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-650

#656 RWA-2845 Migrating to Workload Identity
  charts/wa-case-event-handler/Chart.yaml
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-656

#657 Rwa 2868 flex server infra
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:wa, prd:wa, add-or-update, rel:wa-case-event-handler-pr-657
