Repository hmcts/wa-case-event-handler, pull requests merged in 2024-05, with the labels that each got.

#698 RWA-3325: Extend Suppression
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-698

#699 Allowing messages in the READY state to also be set to PROCESSED so w…
  src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/jobservices/SetStateToProcessedMessageJob.java
  src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/jobservices/SetStateToProcessedMessageJobTest.java
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-699

#703 Update state.tf
  infrastructure/state.tf
Labels: ns:wa, prd:wa, aat/add-or-update, prod/add-or-update, rel:wa-case-event-handler-pr-703
