Repository hmcts/wa-case-event-handler, pull requests merged in 2024-07, with the labels that each got.

#723 RWA-3486: Add env.TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  config/owasp/suppressions.xml
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-723

#697 RWA-3300: Received messages help check repo tests added
  src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/ReceivedMessagesHealthControllerTest.java
  src/integrationTest/resources/scripts/insert_case_event_messages_for_received_messages_check.sql
  src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/repository/CaseEventMessageRepositoryTest.java
  src/test/resources/sql/insert_case_event_messages_for_received_messages_check.sql
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-697

#724 Nightly dev
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-724

#725 Tuning stalebot
  .github/stale.yml
  .github/workflows/stale.yml
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-725

#728 tune renovate
  .github/renovate.json
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-728

#457 RWA-2162 Fix case type issue
  src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/AsbMessagesToDatabaseTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/DlqMessagesToDatabaseTest.java
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-457, WIP
