Repository hmcts/wa-case-event-handler, pull requests merged in 2025-06, with the labels that each got.

#861 RWA-4382 upgrade pitest library issues
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-861

#862 RWA-4238: Removed hardcoded password
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/functionalTest/resources/application-functional.yaml
  src/testUtils/java/uk/gov/hmcts/reform/wacaseeventhandler/services/AuthorizationProvider.java
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-862

#867 RWA-4366: Upgrade owasp
  build.gradle
Labels: ns:wa, prd:wa, rel:wa-case-event-handler-pr-867
